// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_W7HC1ENiOdmgr5FuIURJBOj0Ju5na8',
    appId: '1:479194781192:web:18a752d9d3bbe4d038e3bd',
    messagingSenderId: '479194781192',
    projectId: 'chatter-6bbcf',
    authDomain: 'chatter-6bbcf.firebaseapp.com',
    storageBucket: 'chatter-6bbcf.appspot.com',
    measurementId: 'G-958J0HBHJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8o4C3LwoB-4_2pJFoCNYpUc0kc4FyznY',
    appId: '1:479194781192:android:ca6b9290a3a312e238e3bd',
    messagingSenderId: '479194781192',
    projectId: 'chatter-6bbcf',
    storageBucket: 'chatter-6bbcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjC8PwkJA6SZD1aXD3cd04EyqT--4iwwA',
    appId: '1:479194781192:ios:661228e39c252b5f38e3bd',
    messagingSenderId: '479194781192',
    projectId: 'chatter-6bbcf',
    storageBucket: 'chatter-6bbcf.appspot.com',
    iosClientId: '479194781192-ptpogqlgvv2c556g19irsq7hc0g7nj3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjC8PwkJA6SZD1aXD3cd04EyqT--4iwwA',
    appId: '1:479194781192:ios:661228e39c252b5f38e3bd',
    messagingSenderId: '479194781192',
    projectId: 'chatter-6bbcf',
    storageBucket: 'chatter-6bbcf.appspot.com',
    iosClientId: '479194781192-ptpogqlgvv2c556g19irsq7hc0g7nj3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatter',
  );
}
